# Generated by Django 4.1.2 on 2023-02-24 22:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_tag", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=50, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("category", models.CharField(max_length=200, null=True)),
                ("article", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
