# Generated by Django 4.1.2 on 2023-06-15 09:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Project Manager", "project manager"),
                            ("Developer Programmer", "developer programmer"),
                            ("Quality Assurance", "quality assurance"),
                            ("Team Lead", "team lead"),
                            ("Unassigned", "unassigned"),
                        ],
                        default="Unassigned",
                        max_length=20,
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.company",
                    ),
                ),
            ],
        ),
    ]
