# Generated by Django 4.1.2 on 2023-06-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_company_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("Freeware", "freeware"),
                    ("Shareware", "shareware"),
                    ("Open Source", "open source"),
                    ("Closed Source", "closed source"),
                ],
                default="Open Source",
                max_length=20,
            ),
        ),
    ]
