# Generated by Django 4.1.2 on 2023-06-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_project_public_project_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qualifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "desciptions",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("grade", models.CharField(blank=True, max_length=10, null=True)),
                ("Institution", models.CharField(max_length=50)),
            ],
        ),
    ]
