# Generated by Django 4.1.2 on 2023-06-22 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_qualifications"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qualifications",
            options={"verbose_name_plural": "Qualifications"},
        ),
        migrations.RenameField(
            model_name="qualifications",
            old_name="desciptions",
            new_name="description",
        ),
    ]
