# Generated by Django 4.1.2 on 2023-07-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_alter_qualifications_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dev_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="dev_model",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
