# Generated by Django 5.0.2 on 2024-02-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_user_dev_id_user_dev_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('file', models.FileField(upload_to='logs/')),
            ],
            options={
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
